### ISSUE TITLE
test matrix always needed for PredictSession

### ISSUE THREAD

**Issue by tvandera** [ExaScience/smurff#114]

**Comment by tvandera** [comment]
```
>>> import smurff
>>> sess = smurff.PredictSession("root.ini")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vanderaa/miniconda3/envs/smurff-0.15/lib/python3.7/site-packages/smurff/predict.py", line 180, in __init__
    one_sample = Sample.fromStepFile(step_file, self.root_dir)
  File "/home/vanderaa/miniconda3/envs/smurff-0.15/lib/python3.7/site-packages/smurff/predict.py", line 46, in fromStepFile
    sample.pred_avg = mio.read_matrix(os.path.join(dir_name, cp["predictions"]["pred_avg"]))
  File "/home/vanderaa/miniconda3/envs/smurff-0.15/lib/python3.7/site-packages/matrix_io/__init__.py", line 125, in read_matrix
    return ext_map[ext][0](filename, **kwargs)
  File "/home/vanderaa/miniconda3/envs/smurff-0.15/lib/python3.7/site-packages/matrix_io/__init__.py", line 100, in read_csv
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample-200-predavg.csv'
```
